name: Requiring rebasing to develop

on: 
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check
      run: |
        sudo apt-get install nkf
        ./.github/workflows/requiring-rebasing-to-develop.sh "$GITHUB_REPOSITORY" "${{ secrets.GITHUB_TOKEN }}"
